export default {
    endpoints: {
        apiPrefix: 'https://rda.infect.info/',
        bacteria: 'pathogen.bacterium',
        antibiotics: 'substance.compound',
        resistances: 'rda.data',
        substanceClasses: 'substance.substanceClass',
        regions: 'generics.region',
        countries: 'generics.country',
        ageGroups: 'generics.ageGroup',
        hospitalStatus: 'generics.hospitalStatus',
        guidelineBaseUrl: 'http://guidelines.infect.info/v1/',
        diagnosisClass: 'diagnosisClass',
        therapyPriorities: 'therapyPriority',
        therapyCompounds: 'therapy_compound',
        diagnosisBacteria: 'diagnosis_bacterium',
        dataSources: 'dataSource',
        diagnoses: 'diagnosis',
        guidelines: 'guideline',
        therapies: 'therapy',
    },
    appKeys: {
        googleAnalytics: 'UA-108372802-1',
    },
};
